AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AccountsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "accountNum"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "accountNum"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: AWS-Accounts-Table
